using System;
using System.Collections.Generic;
using System.Globalization;

namespace OpenTabletDriver.UX
{
    public static class Language
    {
        public static bool IsChinese { get; private set; } = true;
        public static event EventHandler? Changed;

        private static readonly Dictionary<string, string> Chinese = new()
        {
            ["Save"] = "保存",
            ["Apply"] = "应用",
            ["Output"] = "输出",
            ["Filters"] = "滤镜",
            ["Pen Settings"] = "笔设置",
            ["Auxiliary Settings"] = "辅助设置",
            ["Mouse Settings"] = "鼠标设置",
            ["Tools"] = "工具",
            ["Info"] = "信息",
            ["Console"] = "控制台",
            ["No tablets are detected."] = "未检测到数位板。",
            ["Copy All"] = "全部复制",
            ["Copy"] = "复制",
            ["Align"] = "对齐",
            ["Resize"] = "调整大小",
            ["Flip"] = "翻转",
            ["Left"] = "左",
            ["Right"] = "右",
            ["Top"] = "上",
            ["Bottom"] = "下",
            ["Center"] = "居中",
            ["Full area"] = "完整区域",
            ["Quarter area"] = "四分之一区域",
            ["Horizontal"] = "水平",
            ["Vertical"] = "垂直",
            ["Lock to usable area"] = "锁定到可用区域",
            ["Language"] = "语言",
            ["Chinese"] = "中文",
            ["English"] = "English",
            ["Quit"] = "退出",
            ["About..."] = "关于...",
            ["Open Wiki..."] = "打开 Wiki...",
            ["Help"] = "帮助",
            ["File"] = "文件",
            ["Tablets"] = "数位板",
            ["Plugins"] = "插件",
            ["Reset to defaults"] = "恢复默认设置",
            ["Tip Settings"] = "笔尖设置",
            ["Tip Binding"] = "笔尖绑定",
            ["Tip Threshold"] = "笔尖触发阈值",
            ["Eraser Settings"] = "橡皮擦设置",
            ["Eraser Binding"] = "橡皮擦绑定",
            ["Eraser Threshold"] = "橡皮擦触发阈值",
            ["Line Stabilization"] = "线条稳定",
            ["Pressure Dead Zone"] = "压力死区",
            ["Elasticity"] = "弹性",
            ["Pressure Filtering"] = "压力滤波",
            ["Retained Peak"] = "保留峰值",
            ["Pen Buttons"] = "笔按键",
            ["Pen Binding"] = "笔按键绑定",
            ["Miscellaneous"] = "其他设置",
            ["Disable Pressure"] = "禁用压感",
            ["Disable Tilt"] = "禁用倾斜",
            ["Disable Rotation"] = "禁用旋转",
            ["Drag Bindings"] = "按压时触发绑定",
            ["Disable pressure if it is available"] = "禁用设备支持的压感输入",
            ["Disable tilt if it is available"] = "禁用设备支持的倾斜输入",
            ["Disable rotation if it is available"] = "禁用设备支持的旋转输入",
            ["Pen Bindings require pressure to activate"] = "笔按键绑定仅在笔尖施加压力时触发",
            ["The minimum threshold in order for the assigned binding to activate."] = "触发所分配绑定所需的最小压力阈值。",
            ["The minimum threshold in degrees in order for the assigned binding to activate."] = "触发所分配绑定所需的最小旋转角度。",
            ["Wheel {0} Bindings"] = "滚轮 {0} 绑定",
            ["Wheel Buttons"] = "滚轮按键",
            ["Wheel Button Binding"] = "滚轮按键绑定",
            ["Clockwise Rotation Settings"] = "顺时针旋转设置",
            ["Clockwise Rotation"] = "顺时针旋转",
            ["Clockwise Rotation Threshold"] = "顺时针旋转阈值",
            ["Counter-Clockwise Rotation Settings"] = "逆时针旋转设置",
            ["Counter-Clockwise Rotation"] = "逆时针旋转",
            ["Counter-Clockwise Rotation Threshold"] = "逆时针旋转阈值",
            ["Mouse Buttons"] = "鼠标按键",
            ["Mouse Scrollwheel"] = "鼠标滚轮",
            ["Mouse Binding"] = "鼠标按键绑定",
            ["Scroll Up"] = "向上滚动",
            ["Scroll Down"] = "向下滚动",
            ["Primary Binding"] = "主键绑定",
            ["Alternate Binding"] = "副键绑定",
            ["Middle Binding"] = "中键绑定",
            ["Auxiliary"] = "辅助按键",
            ["Auxiliary Binding"] = "辅助按键绑定",
            ["Display"] = "显示器",
            ["Tablet"] = "数位板",
            ["Width"] = "宽度",
            ["Height"] = "高度",
            ["Rotation"] = "旋转",
            ["Relative"] = "相对模式",
            ["X Sensitivity"] = "X 轴灵敏度",
            ["Y Sensitivity"] = "Y 轴灵敏度",
            ["Reset Time"] = "重置时间",
            ["Area width in {0}"] = "区域宽度（{0}）",
            ["Area height in {0}"] = "区域高度（{0}）",
            ["Area center X offset in {0}"] = "区域中心 X 坐标（{0}）",
            ["Area center Y offset in {0}"] = "区域中心 Y 坐标（{0}）",
            ["Angle of rotation about the center of the area."] = "围绕区域中心旋转的角度。",
            ["Invalid display area."] = "显示区域无效。",
            ["Invalid tablet area."] = "数位板区域无效。",
            ["Lock aspect ratio"] = "锁定宽高比",
            ["Clamp input outside area"] = "将区域外输入限制到边界",
            ["Ignore input outside area"] = "忽略区域外输入",
            ["Convert area..."] = "转换区域...",
            ["Convert Area..."] = "转换区域...",
            ["Converter"] = "转换器",
            ["Handedness"] = "左右手切换",
            ["Set to display"] = "设为显示器",
            ["Display {0} ({1}x{2}@{3})"] = "显示器 {0}（{1}x{2}@{3}）",
            ["Virtual Screen"] = "虚拟屏幕",
            ["You can right click the area editor to set the area to a display, adjust alignment, or resize the area."] = "右键点击区域编辑器，可设为显示器区域、调整对齐或更改区域大小。",
            ["You can right click the area editor to enable aspect ratio locking, adjust alignment, or resize the area."] = "右键点击区域编辑器，可锁定宽高比、调整对齐或更改区域大小。",
            ["Absolute Mode"] = "绝对模式",
            ["Relative Mode"] = "相对模式",
            ["Artist Mode"] = "绘画模式",
            ["Windows Ink Absolute Mode"] = "Windows Ink 绝对模式",
            ["Windows Ink Relative Mode"] = "Windows Ink 相对模式",
            ["No supported output mode selected."] = "未选择受支持的输出模式。",
            ["No tablets were detected or selected."] = "未检测到或未选择数位板。",
            ["No plugins containing this type are installed."] = "尚未安装此类型的插件。",
            ["Open Plugin Manager"] = "打开插件管理器",
            ["Open Plugin Manager..."] = "打开插件管理器...",
            ["Enable {0}"] = "启用 {0}",
            ["Adaptive Binding"] = "自适应绑定",
            ["Binding"] = "绑定",
            ["Tip"] = "笔尖",
            ["Eraser"] = "橡皮擦",
            ["Button 1"] = "按键 1",
            ["Button 2"] = "按键 2",
            ["Button 3"] = "按键 3",
            ["Button {0}"] = "按键 {0}",
            ["Mouse Button Binding"] = "鼠标按键绑定",
            ["Mouse Scroll Binding"] = "鼠标滚轮绑定",
            ["Keyboard Binding"] = "键盘绑定",
            ["Pen Passthrough"] = "笔输入直通",
            ["Disabled"] = "禁用",
            ["None"] = "无",
            ["Middle"] = "中键",
            ["Forward"] = "前进",
            ["Backward"] = "后退",
            ["Up"] = "上",
            ["Down"] = "下",
            ["Button"] = "按键",
            ["Key"] = "按键",
            ["Scroll Direction"] = "滚动方向",
            ["Binding Editor"] = "绑定编辑器",
            ["Advanced Binding Editor"] = "高级绑定编辑器",
            ["Clear"] = "清除",
            ["Type"] = "类型",
            ["Press a key, combination of keys, or a mouse button."] = "请按下键盘按键、组合键或鼠标按键。",
            ["Connecting to OpenTabletDriver Daemon..."] = "正在连接 OpenTabletDriver 后台服务...",
            ["Load settings..."] = "加载设置...",
            ["Save settings as..."] = "设置另存为...",
            ["Save settings"] = "保存设置",
            ["Apply settings"] = "应用设置",
            ["Refresh presets"] = "刷新预设",
            ["Save as preset..."] = "另存为预设...",
            ["Open presets directory..."] = "打开预设目录...",
            ["Detect tablet"] = "检测数位板",
            ["Tablet debugger..."] = "数位板调试器...",
            ["Device string reader..."] = "设备字符串读取器...",
            ["Show guide..."] = "显示使用指南...",
            ["Export diagnostics..."] = "导出诊断信息...",
            ["Export diagnostics to Clipboard..."] = "将诊断信息复制到剪贴板...",
            ["Check for updates..."] = "检查更新...",
            ["Presets"] = "预设",
            ["No presets loaded"] = "未加载预设",
            ["Show Window"] = "显示窗口",
            ["Show OpenTabletDriver"] = "显示 OpenTabletDriver",
            ["Close"] = "关闭",
            ["Time"] = "时间",
            ["Level"] = "级别",
            ["Group"] = "分组",
            ["Message"] = "消息",
            ["Debug"] = "调试",
            ["Warning"] = "警告",
            ["Error"] = "错误",
            ["Fatal"] = "严重错误",
            ["About"] = "关于",
            ["About OpenTabletDriver"] = "关于 OpenTabletDriver",
            ["Open source, cross-platform tablet configurator"] = "开源、跨平台的数位板配置工具",
            ["OpenTabletDriver Github Repository"] = "OpenTabletDriver GitHub 仓库",
            ["In memory of jamesbt365"] = "纪念 jamesbt365",
            ["Credits"] = "贡献者",
            ["License"] = "许可证",
            ["Memoriam"] = "纪念",
            ["Cancel"] = "取消",
            ["Ok"] = "确定",
            ["Application Error"] = "应用错误",
            ["An application error has occured. Report this to the developers!"] = "应用发生错误，请向开发者报告！",
            ["Reports Recorded"] = "已记录的报告",
            ["Visualizer"] = "可视化",
            ["Additional Stats"] = "附加统计",
            ["No stats observed yet"] = "暂无统计数据",
            ["Debugged Reports"] = "调试报告",
            ["Debugged Tablets"] = "调试数位板",
            ["Device"] = "设备",
            ["Report Rate"] = "报告率",
            ["Tablet Report"] = "数位板报告",
            ["Raw Tablet Data"] = "原始数位板数据",
            ["Data Recording"] = "数据记录",
            ["Open recordings directory..."] = "打开记录目录...",
            ["Recording"] = "记录中",
            ["Raw Data Mode"] = "原始数据模式",
            ["Additional Statistics"] = "附加统计",
            ["Close Window"] = "关闭窗口",
            ["Force Refresh"] = "强制刷新",
            ["Send Request"] = "发送请求",
            ["Dump All"] = "读取全部",
            ["WARNING\nArbitrary use of this tool may cause damage or disrupt usage of your tablet"] = "警告\n随意使用此工具可能损坏数位板或影响其正常使用",
            ["Device String"] = "设备字符串",
            ["Device String Reader"] = "设备字符串读取器",
            ["Require reconnect on fail"] = "失败时要求重新连接",
            ["Dump potentially dangerous strings"] = "读取可能有风险的字符串",
            ["Pauses string dump with a pop-up box if any string dump errors occur"] = "读取字符串出错时弹出提示并暂停读取",
            ["Requests all strings in a string dump even if they are known to likely damage or disrupt usage of the tablet"] = "请求所有字符串，包括已知可能损坏数位板或影响其使用的字符串",
            ["Checking for updates..."] = "正在检查更新...",
            ["Go to Release"] = "前往发布页面",
            ["Open Directory"] = "打开目录",
            ["No updates are available."] = "当前已是最新版本。",
            ["OpenTabletDriver Updater"] = "OpenTabletDriver 更新器",
            ["Uninstall"] = "卸载",
            ["Name"] = "名称",
            ["Owner"] = "所有者",
            ["Creator"] = "作者",
            ["Description"] = "说明",
            ["Driver Version"] = "驱动版本",
            ["Max Supported Driver Version"] = "支持的最高驱动版本",
            ["Plugin Version"] = "插件版本",
            ["Source Code Repository"] = "源代码仓库",
            ["Show source code"] = "查看源代码",
            ["Wiki"] = "Wiki",
            ["Show plugin wiki"] = "查看插件 Wiki",
            ["No plugin selected."] = "未选择插件。",
            ["Drag and drop plugins here to install."] = "将插件拖放到此处安装。",
            ["Exit"] = "退出",
            ["Install plugin..."] = "安装插件...",
            ["Refresh"] = "刷新",
            ["Use alternate source..."] = "使用其他源...",
            ["Open plugins directory..."] = "打开插件目录...",
            ["Plugin Manager"] = "插件管理器",
            ["Demo Area Editor"] = "区域编辑器示例",
            ["Demo"] = "示例",
            ["Demo Binding"] = "绑定示例",
            ["Next"] = "下一步",
            ["Previous"] = "上一步",
            ["OpenTabletDriver Guide"] = "OpenTabletDriver 使用指南",
            ["Ref"] = "分支或引用",
            ["Reset settings to default?"] = "将设置恢复为默认值？",
        };

        public static string T(string text) =>
            IsChinese && Chinese.TryGetValue(text, out var translated) ? translated : text;

        public static string Format(string text, params object?[] args) =>
            string.Format(CultureInfo.CurrentCulture, T(text), args);

        public static T Localize<T>(this T target, Action<T> update)
        {
            update(target);
            Changed += (_, _) => update(target);
            return target;
        }

        public static void SetChinese(bool chinese)
        {
            if (IsChinese == chinese) return;
            IsChinese = chinese;
            Changed?.Invoke(null, EventArgs.Empty);
        }
    }
}
